### ISSUE TITLE
[PE-D] corrupted addressbook.json data

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-1/tp#168]
if i edit the json file and it gets corrupted, there is no error message upon startup and the file is completely deleted.
One possible way would be to change the file name of the corrupted file and give the user an error message so that the user can try to manually save their data.

![image.png](https://raw.githubusercontent.com/muhammad-faruq/ped/master/files/cbd39f42-8292-4903-a246-35849531b247.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: muhammad-faruq/ped#8

**Comment by ziqing26** [comment]
Possible to show error message?
