### ISSUE TITLE
[PE-D] Last visit can be in the future

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-1/tp#171]
![image.png](https://raw.githubusercontent.com/muhammad-faruq/ped/master/files/e82c2403-c636-4e8a-81c3-f14884740e68.png)

the last visit component is allowed to be a date in the future.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: muhammad-faruq/ped#9

**Comment by ziqing26** [comment]
Warning message in yellow for a future date.
