### ISSUE TITLE
[PE-D] Consider changing the formatting for examples under Add in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-1/tp#177]
![image.png](https://raw.githubusercontent.com/shaliniseshadri/ped/main/files/615232a3-9b64-406b-af30-d9e02a6c34b6.png)

The text in the above image is fairly hard to read because of the formatting of the inline code. Maybe the formatting could be changed so that it would be easier to read?

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: shaliniseshadri/ped#6

**Comment by ziqing26** [comment]
![image](https://user-images.githubusercontent.com/69516975/139534040-754a0771-2ce9-4f28-b8c0-96d8c50d1d89.png)
