### ISSUE TITLE
[PE-D] Phone numbers do not accept valid phone numbers with country code e.g. +60

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103-T14-1/tp#178]
Phone numbers currently only allows for numeric inputs, and do not accept the inclusion of country code added prior to the phone numbers, in the case that the senior has a phone number from out of country.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: ryanpeh/ped#5

**Comment by huisthat** [comment]
Possible to specify in user guide that we assume that all seniors have a local phone number?

**Comment by ziqing26** [comment]
Link #154 -  add restriction to phone number 
- only 8 digits 
- add to user guide

**Comment by luayida99** [comment]
UG has been updated
