### ISSUE TITLE
Add use cases to DG

### ISSUE THREAD

**Issue by ailing35** [AY2122S1-CS2103-T14-1/tp#202]
- [x] visit (with and without f/ and o/) @huisthat 
- [x] delete visit @huisthat 
- [x] sort visit @huisthat 
- [ ] list (week and month) @Chen-Yiyang 
- [x] edit @luayida99

**Comment by luayida99** [comment]
@Chen-Yiyang noticed that there was a missing **MSS** on line 658 of the DG, do you mind helping to add that in and doing a final check on the DG? Thanks
