### ISSUE TITLE
As a social worker, I can add recurring deadlines to contact the elderly

### ISSUE THREAD

**Issue by huisthat** [AY2122S1-CS2103-T14-1/tp#57]
... so that I do not have to schedule one by one.

**Comment by ziqing26** [comment]
- [ ] Frequency Enum @ziqing26 
- [ ] Add optional flags to visit command @huisthat 
- [ ] Fix conflicts in existing test cases. @huisthat 
- [ ] Add additional test cases. @ziqing26
