### ISSUE TITLE
Change visit and last visit to take in date time instead of date

### ISSUE THREAD

**Issue by ailing35** [AY2122S1-CS2103-T14-1/tp#59]
- In line with changes to visit, users can track the time of the last visit.

**Comment by Chen-Yiyang** [comment]
Yes, I will work on this over the weekend 👍

**Comment by Chen-Yiyang** [comment]
Implementation
- [ ] Use date & time for both visit and last visited (instead of just date)
- [ ] Update datetime storage format (stored as `yyyy-mm-dd hh-mm` and displayed using text. Refer to the UG for more details)
