### ISSUE TITLE
Test coverage: add tests for DoneCommandParser and VisitCommandParser

### ISSUE THREAD

**Issue by ziqing26** [AY2122S1-CS2103-T14-1/tp#69]
DoneCommandParser and VisitCommandParser do not have tests for valid arguments. An example of such test is:
![image](https://user-images.githubusercontent.com/69516975/136670164-f65c3913-b0ca-4df4-b052-07d5b9d21929.png)

- [x] Add tests for DoneCommandParser
- [x] Add tests for VisitCommandParser

**Comment by Chen-Yiyang** [comment]
Noted!

**Comment by luayida99** [comment]
Added valid argument test for VisitCommandParser and added parsing test for done in AddressBookParserTest
